name: Development 


on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "Dev" ]
  pull_request:
    branches: [ "Dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: sort videos
        run: |
          git clone https://github.com/omxpro/reddit-videos.git        
          cd reddit-videos
          touch README.md
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: üëç New reddit videos from $(date +%F)
